### ISSUE TITLE
Add it to packagist

### ISSUE THREAD

**Issue by elboletaire** [ciricihq/MatchAgainstBundle#1]

**Comment by robations** [comment]
[link here](https://packagist.org/login/) :)

**Comment by elboletaire** [comment]
haha thanks, we already know how to do it, but we've not much time for it. I'll try to do it tomorrow :wink:

**Comment by robations** [comment]
Thanks! People seem to like to blog examples how to do this, rather than create a reusable package. Yours looks one of the better ones :+1:

**Comment by elboletaire** [comment]
Sorry! I forgot that it is in fact already on packagist: https://packagist.org/packages/ciricihq/match-against-bundle

I close the issue then :smiley: 

Thank you for your comments! Note that the credits for this bundle go to @gtrias :smile:
